updated configures with fixed saga detection macro A
git-svn-id: file://localhost/tmp/svn2git/saga-wg/svn@83 bd306f8e-b875-4415-8b40-16139df0eb6e

diff --git a/ssh/trunk/configure b/ssh/trunk/configure
--- a/ssh/trunk/configure
+++ b/ssh/trunk/configure
@@ -1718,27 +1718,6 @@ echo $ECHO_N "checking SAGA installation/sources... $ECHO_C" >&6; }
 
 
   # check SAGA_ROOT - prefer over SAGA_LOCATION and saga-config
-  if test "x$SAGA_ROOT" = "x"; then
-
-    # try ./, ../ and ../../ as SAGA_ROOT
-
-    if test -e ./make/saga.mk; then
-      SAGA_ROOT=`pwd`
-    fi
-
-    if test -e ../make/saga.mk; then
-      SAGA_ROOT=`pwd`/..
-    fi
-
-    if test -e ../../make/saga.mk; then
-      SAGA_ROOT=`pwd`/../../
-    fi
-
-    if test -e ../../../make/saga.mk; then
-      SAGA_ROOT=`pwd`/../../../
-    fi
-  fi
-
   if test "x$SAGA_ROOT" != "x"; then
     TMP_SAGA_LOCATION=$SAGA_ROOT
     TMP_SAGA_INSTTYPE="source"
@@ -1769,6 +1748,11 @@ echo "${ECHO_T}$TMP_SAGA_LOCATION ($TMP_SAGA_INSTTYPE)" >&6; }
     SAGA_CONFIG_DIR="$TMP_SAGA_LOCATION/share/saga/config"
   fi
 
+  if ! test -e "$SAGA_CONFIG_DIR/saga-config.cache"; then
+    { { echo "$as_me:$LINENO: error: SAGA $TMP_SAGA_INSTTYPE tree seems invalid, no saga-config.cache found." >&5
+echo "$as_me: error: SAGA $TMP_SAGA_INSTTYPE tree seems invalid, no saga-config.cache found." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
   source "$SAGA_CONFIG_DIR/saga-config.cache"
 
 
@@ -2095,22 +2079,25 @@ BUILD_ADAPTOR_FILESYSTEM=no
 BUILD_ADAPTOR_JOB=no
 
 if test "x$HAVE_SSH" = "xyes"; then
-
   if test "x$SAGA_HAVE_ADAPTOR_CONTEXT" = "xyes"; then
     BUILD_ADAPTOR_CONTEXT="yes"
   fi
+fi
 
+if test "x$HAVE_SSH" = "xyes"; then
   if test "x$SAGA_HAVE_ADAPTOR_JOB" = "xyes"; then
     BUILD_ADAPTOR_JOB="yes"
+    BUILD_ADAPTOR_CONTEXT="yes"
   fi
-
-  if test "$HAVE_SSHFS-$HAVE_SCP" = "yes-yes"; then
-    if test "x$SAGA_HAVE_ADAPTOR_FILESYSTEM" = "xyes"; then
-      BUILD_ADAPTOR_FILESYSTEM="yes"
-    fi
-  fi
-
 fi
+
+if test "$HAVE_SSHFS-$HAVE_SCP" = "yes-yes"; then
+  if test "x$SAGA_HAVE_ADAPTOR_FILESYSTEM" = "xyes"; then
+    BUILD_ADAPTOR_FILESYSTEM="yes"
+    BUILD_ADAPTOR_CONTEXT="yes"
+  fi
+fi
+
 
 if test "x$HAVE_SSH" = "xyes"; then
   SAGA_SSH_S="($SAGA_SSH)"
